export default (text = 'Text generated by h1.js') => {
  const element = document.createElement('h1');

  element.innerHTML = text;
  // PurifyCSS can detect dynamic added classes
  element.className = 'textUnderline';

  return element;
};